@echo off
SETLOCAL

REM Debug Echos

REM The arguments from MSBuild
SET TARGET_PATH=%~1
SET TARGET_DIR=%~2
SET TARGET_NAME=%~3
SET PUBLIC_DIR=%~4
SET APPDATA_DIR=%~5
SET CONFIGURATION=%~6

SET VERSION=2025
SET OEM_PROJECT_NAME=TinCAD

ECHO "TARGET_PATH="%TARGET_PATH%
ECHO "TARGET_DIR="%TARGET_DIR%
ECHO "TARGET_NAME="%TARGET_NAME%
ECHO "PUBLIC_DIR="%PUBLIC_DIR%
ECHO "APPDATA_DIR="%APPDATA_DIR%
ECHO "CONFIGURATION"=%CONFIGURATION%

SET "INSTALL_DIRECTORY=%PUBLIC_DIR%\Documents\AutoCAD OEM %VERSION%\Build\%OEM_PROJECT_NAME%\TinDll"
ECHO "INSTALL_DIRECTORY="%INSTALL_DIRECTORY%

SET "BINDTOOLEXE=C:\Program Files\Autodesk\AutoCAD OEM %VERSION% - English\Toolkit\bindmgd.exe"
SET "BINDTOOL_PATH=C:\Program Files\Autodesk\AutoCAD OEM %VERSION% - English\Toolkit\"

IF NOT EXIST "%BINDTOOLEXE%" (
    ECHO %BINDTOOLEXE%
    ECHO Bindtool exe e.g bindmgd.exe is missing...
    GOTO End
)

SET "SNK_FILE_PATH=%PUBLIC_DIR%\Documents\AutoCAD OEM %VERSION%\Projects\%OEM_PROJECT_NAME%\Toolkit\%OEM_PROJECT_NAME%.snk"
SET "DLL_FILE=%TARGET_DIR%%TARGET_NAME%.dll"

ECHO "DLL_FILE="%DLL_FILE%
ECHO "SNK_FILE_PATH="%SNK_FILE_PATH%

IF NOT EXIST "%SNK_FILE_PATH%" (
    ECHO %SNK_FILE_PATH%
    ECHO SNK File is missing...
    GOTO End
)

REM set current directory
cd %BINDTOOL_PATH%
bindmgd.exe -b "%DLL_FILE%" "%SNK_FILE_PATH%"

REM Copy Dll
ECHO Copying DLL...
xcopy "%TARGET_DIR%%TARGET_NAME%.dll" "%INSTALL_DIRECTORY%"  /F /R /Y /I
xcopy "%TARGET_DIR%%TARGET_NAME%.dll.sig" "%INSTALL_DIRECTORY%" /F /R /Y /I



IF ERRORLEVEL 1 (
    ECHO Failed to copy DLL to public documents folder
    GOTO End
)

:End

ENDLOCAL