@echo off
SETLOCAL

REM Debug Echos

REM The arguments from MSBuild
SET TARGET_PATH=%~1
SET TARGET_DIR=%~2
SET TARGET_NAME=%~3
SET PUBLIC_DIR=%~4
SET APPDATA_DIR=%~5
SET CONFIGURATION=%~6

SET VERSION=2025
SET OEM_PROJECT_NAME=TinCAD

ECHO "TARGET_PATH="%TARGET_PATH%
ECHO "TARGET_DIR="%TARGET_DIR%
ECHO "TARGET_NAME="%TARGET_NAME%
ECHO "PUBLIC_DIR="%PUBLIC_DIR%
ECHO "APPDATA_DIR="%APPDATA_DIR%
ECHO "CONFIGURATION"=%CONFIGURATION%

SET "INSTALL_DIRECTORY=%PUBLIC_DIR%\Documents\AutoCAD OEM %VERSION%\Build\%OEM_PROJECT_NAME%"
ECHO "INSTALL_DIRECTORY="%INSTALL_DIRECTORY%

REM Copy Dll
xcopy "%TARGET_DIR%%TARGET_NAME%.dll" "%INSTALL_DIRECTORY%"  /F /R /Y /I


IF ERRORLEVEL 1 (
    ECHO Failed to copy DLL to public documents folder
    GOTO End
)

:End

ENDLOCAL